In [1]:
from sklearn.decomposition import TruncatedSVD
from scipy.sparse import random as sparse_random
X = sparse_random(100, 100, density=0.01, format='csr',
                  random_state=42)
svd = TruncatedSVD(n_components=5, n_iter=7, random_state=42)
svd.fit(X)

print(svd.explained_variance_ratio_)

print(svd.explained_variance_ratio_.sum())

print(svd.singular_values_)

[0.06460458 0.06339574 0.06394296 0.05352982 0.04061973]
0.286092835213789
[1.55360944 1.5121377  1.51052009 1.37056529 1.19917045]


In [2]:
type(X)

scipy.sparse.csr.csr_matrix

In [3]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
messages = ['call you tonight','call me a cab', 'please call me.. please']
df = pd.DataFrame({'messages':messages})
df.head()

messages
0         call you tonight
1            call me a cab
2  please call me.. please

## Get term frequency

In [5]:

vect = CountVectorizer()
vect.fit(df.messages)
names = vect.get_feature_names()
names

['cab', 'call', 'me', 'please', 'tonight', 'you']

In [6]:
transformed = vect.transform(df.messages)
print(transformed.toarray())

[[0 1 0 0 1 1]
 [1 1 1 0 0 0]
 [0 1 1 2 0 0]]


In [7]:
print(df.messages)

0           call you tonight
1              call me a cab
2    please call me.. please
Name: messages, dtype: object


In [8]:
tf = pd.DataFrame(transformed.toarray())
tf.columns = names
tf.head()

cab  call  me  please  tonight  you
0    0     1   0       0        1    1
1    1     1   1       0        0    0
2    0     1   1       2        0    0

In [9]:
tf.loc[0,'outcome'] = 'info'
tf.loc[1,'outcome'] = 'order'
tf.loc[2,'outcome'] = 'request'
tf.head()

cab  call  me  please  tonight  you  outcome
0    0     1   0       0        1    1     info
1    1     1   1       0        0    0    order
2    0     1   1       2        0    0  request

# get Term Frequency inverse Document Frequency

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf_idf = TfidfVectorizer()
trans  = tf_idf.fit_transform(df.messages)
idf = pd.DataFrame(trans.toarray(),columns = tf_idf.get_feature_names())
idf.head()

cab      call        me    please   tonight       you
0  0.000000  0.385372  0.000000  0.000000  0.652491  0.652491
1  0.720333  0.425441  0.547832  0.000000  0.000000  0.000000
2  0.000000  0.266075  0.342620  0.901008  0.000000  0.000000

In [11]:
from sklearn.decomposition import TruncatedSVD
svd = TruncatedSVD(n_components=5, n_iter=7, random_state=42)
svd.fit(df.messages)

print(svd.explained_variance_ratio_)

print(svd.explained_variance_ratio_.sum())

print(svd.singular_values_)

ValueError: could not convert string to float: 'call you tonight'